from pathlib import Path

DATASETS = {
    "agriculture": {"label": "Agriculture Loan", "file": "data_sets/agriculture_loan_data.csv"},
    "bike": {"label": "Bike Loan", "file": "data_sets/bike_loans.csv"},
    "business": {"label": "Business Loan", "file": "data_sets/business_loans.csv"},
    "car": {"label": "Car Loan", "file": "data_sets/car_loans.csv"},
    "education": {"label": "Education Loan", "file": "data_sets/education_loans.csv"},
    "home": {"label": "Home Loan", "file": "data_sets/home_loans.csv"},
    "personal": {"label": "Personal Loan", "file": "data_sets/personal_loans.csv"},
}

FIELD_LABELS = {
    "age": "Applicant Age",
    "annual_income": "Annual Income",
    "annual_revenue": "Annual Revenue",
    "annual_farm_revenue": "Annual Farm Revenue",
    "alt_annual_income": "Alternate Annual Income",
    "alt_income_source": "Alternate Income Source",
    "applicant_age": "Applicant Age",
    "bike_price": "Bike Price",
    "car_price": "Car Price",
    "car_type": "Car Type",
    "collateral_type": "Collateral Type",
    "collateral_value": "Collateral Value",
    "course_category": "Course Category",
    "credit_score": "Credit Score",
    "down_payment": "Down Payment",
    "dscr": "DSCR",
    "dti_ratio": "DTI Ratio",
    "emp_status": "Employment Status",
    "employment_tenure_years": "Employment Tenure (Years)",
    "existing_monthly_emi": "Existing Monthly EMI",
    "farmer_age": "Farmer Age",
    "foir_ratio": "FOIR Ratio",
    "gpa": "GPA",
    "income": "Annual Income",
    "industry_type": "Industry Type",
    "land_acres": "Land Size (Acres)",
    "loan_amount": "Loan Amount",
    "loan_amount_requested": "Loan Amount Requested",
    "loan_purpose": "Loan Purpose",
    "loan_term": "Loan Term (Months)",
    "loan_term_months": "Loan Term (Months)",
    "ltv_ratio": "LTV Ratio",
    "net_profit": "Net Profit",
    "owner_credit_score": "Owner Credit Score",
    "parent_annual_income": "Parent Annual Income",
    "parent_credit_score": "Parent Credit Score",
    "property_value": "Property Value",
    "requested_amount": "Requested Amount",
    "tenure_years": "Tenure (Years)",
    "total_annual_income": "Total Annual Income",
    "uni_ranking": "University Ranking",
    "years_experience": "Years of Experience",
    "years_in_business": "Years in Business",
}

RECOMMENDATION_HINTS = {
    "credit_score": "improve the credit profile or add a stronger co-applicant",
    "owner_credit_score": "improve the credit profile before reapplying",
    "parent_credit_score": "strengthen the guarantor or parent credit profile",
    "annual_income": "show higher stable income or lower the requested amount",
    "income": "show higher stable income or reduce the financed amount",
    "annual_revenue": "provide stronger revenue proof or request a smaller loan",
    "annual_farm_revenue": "provide stronger farm revenue evidence or request a smaller amount",
    "net_profit": "improve profitability and supporting business documents",
    "down_payment": "increase the down payment to lower financing risk",
    "ltv_ratio": "lower the LTV by increasing upfront contribution",
    "dti_ratio": "reduce existing debt obligations before reapplying",
    "foir_ratio": "lower current obligations to improve repayment capacity",
    "existing_monthly_emi": "reduce ongoing EMI burden before taking a new loan",
    "loan_amount": "request a smaller loan amount",
    "loan_amount_requested": "request a smaller loan amount",
    "requested_amount": "request a smaller business loan amount",
    "property_value": "choose a lower-risk property or increase the down payment",
    "collateral_value": "offer stronger collateral coverage",
    "dscr": "improve cash flow coverage for the requested installment",
    "gpa": "strengthen academic performance or add a stronger repayment plan",
    "uni_ranking": "target a better-ranked program or show stronger funding support",
}
